version: '3.7'

services:
  jenkins:
    image: bitnami/jenkins:latest
    container_name: jenkins
    restart: always
    environment:
      - JENKINS_PASSWORD=bitnami
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - "./data/jenkins:/var/jenkins_home"
    networks:
      - app

networks:
  app:
    driver: bridge